const mongoose = require('mongoose')
const Schema = mongoose.Schema

const billsSchema = new Schema({
    // userId:{
    //     type:Schema.Types.ObjectId,
    //     ref:'mobileusers'
    // },
    invoiceNumber:{
        type:String
    },
    HSN_SAC:{
        type:String
    },
    Date:{
        type:String  
    },
    partyName:{
        type:String
    },
    partyMobileNumber:{
        type:String
    },
    advance:{
        type:Number,
        default:0
    },
    billStatus:{
        type:String,
        default:"Pending"
    },
    withGST:{
        type:String,
        default:"No"
    },
    GSTAmount:{
        type:Number,
        default:0
    },
    parti1:{
        type:String,
        default:''
    },
    parti2:{
        type:String,
        default:''
    },
    parti3:{
        type:String,
        default:''
    },
    parti4:{
        type:String,
        default:''
    },
    parti5:{
        type:String,
        default:''
    },
    parti6:{
        type:String,
        default:''
    },
    parti7:{
        type:String,
        default:''
    },
    parti8:{
        type:String,
        default:''
    },
    parti9:{
        type:String,
        default:''
    },
    parti10:{
        type:String,
        default:''
    },
    sq1:{
        type:Number,
        default:0
    },
    sq2:{
        type:Number,
        default:0
    },
    sq3:{
        type:Number,
        default:0
    },
    sq4:{
        type:Number,
        default:0
    },
    sq5:{
        type:Number,
        default:0
    },
    sq6:{
        type:Number,
        default:0
    },
    sq7:{
        type:Number,
        default:0
    },
    sq8:{
        type:Number,
        default:0
    },
    sq9:{
        type:Number,
        default:0
    },
    sq10:{
        type:Number,
        default:0
    },
    rate1:{
        type:Number,
        default:0
    },
    rate2:{
        type:Number,
        default:0
    },
    rate3:{
        type:Number,
        default:0
    },
    rate4:{
        type:Number,
        default:0
    },
    rate5:{
        type:Number,
        default:0
    },
    rate6:{
        type:Number,
        default:0
    },
    rate7:{
        type:Number,
        default:0
    },
    rate8:{
        type:Number,
        default:0
    },
    rate9:{
        type:Number,
        default:0
    },
    rate10:{
        type:Number,
        default:0
    },
    Total1:{
        type:Number,
        default:0
    },
    Total2:{
        type:Number,
        default:0
    },
    Total3:{
        type:Number,
        default:0
    },
    Total4:{
        type:Number,
        default:0
    },
    Total5:{
        type:Number,
        default:0
    },
    Total6:{
        type:Number,
        default:0
    },
    Total7:{
        type:Number,
        default:0
    },
    Total8:{
        type:Number,
        default:0
    },
    Total9:{
        type:Number,
        default:0
    },
    Total10:{
        type:Number,
        default:0
    },
    Total11:{
        type:Number,
        default:0
    },
    width1:{
        type:Number,
        default:0
    },
    width2:{
        type:Number,
        default:0
    },
    width3:{
        type:Number,
        default:0
    },
    width4:{
        type:Number,
        default:0
    },
    width5:{
        type:Number,
        default:0
    },
    width6:{
        type:Number,
        default:0
    },
    width7:{
        type:Number,
        default:0
    },
    width8:{
        type:Number,
        default:0
    },
    width9:{
        type:Number,
        default:0
    },
    width10:{
        type:Number,
        default:0
    },
    height1:{
        type:Number,
        default:0
    },
    height2:{
        type:Number,
        default:0
    },
    height3:{
        type:Number,
        default:0
    },
    height4:{
        type:Number,
        default:0
    },
    height5:{
        type:Number,
        default:0
    },
    height6:{
        type:Number,
        default:0
    },
    height7:{
        type:Number,
        default:0
    },
    height8:{
        type:Number,
        default:0
    },
    height9:{
        type:Number,
        default:0
    },
    height10:{
        type:Number,
        default:0
    },
    GSTNo:{
        type:String
    },
    partyAddress:{
        type:String
    },
    active:{
        type:Boolean,
        default:true
    }
}, {
    timestamps: true
});

module.exports = mongoose.model('bills', billsSchema)